<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2 Assignment 2*

# Document Representations: Bag-Of-Words

In [2]:
import re
import string

# !pip install -U nltk

import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import sent_tokenize # Sentence Tokenizer
from nltk.tokenize import word_tokenize # Word Tokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.probability import FreqDist

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Patrick\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Patrick\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# 1) (optional) Scrape 100 Job Listings that contain the title "Data Scientist" from indeed.com

At a minimum your final dataframe of job listings should contain
- Job Title
- Job Description

If you choose to not to scrape the data, there is a CSV with outdated data in the directory. Remeber, if you scrape Indeed, you're helping yourself find a job. ;)

In [3]:
import pandas as pd
df = pd.read_csv('./job_listings.csv')


In [4]:
df.head()

Unnamed: 0                                        description  \
0           0  b"<div><div>Job Requirements:</div><ul><li><p>...   
1           1  b'<div>Job Description<br/>\n<br/>\n<p>As a Da...   
2           2  b'<div><p>As a Data Scientist you will be work...   
3           3  b'<div class="jobsearch-JobMetadataHeader icl-...   
4           4  b'<ul><li>Location: USA \xe2\x80\x93 multiple ...   

                          title  
0               Data scientist   
1              Data Scientist I  
2  Data Scientist - Entry Level  
3                Data Scientist  
4                Data Scientist

## 2) Use Spacy to tokenize / clean the listings 

In [5]:
import spacy
from spacy.tokenizer import Tokenizer
nlp = spacy.load("en_core_web_lg")

text = df.description 

tokenizer = Tokenizer(nlp.vocab)

tokens = []
STOP_WORDS = nlp.Defaults.stop_words.union(['\n', '\n\n', 'The', 'I', '<div>', 'b"<div><div>',])

for doc in tokenizer.pipe(df['description'], batch_size=500):
    doc_tokens = []
    
    for token in doc:
        if token.text not in STOP_WORDS:
            doc_tokens.append(token.text.lower())
    tokens.append(doc_tokens)
    
df['tokens'] = tokens


In [81]:
df['tokens'].head()

0    [b"<div><div>job, requirements:</div><ul><li><...
1    [b'<div>job, description<br/>\n<br/>\n<p>as, d...
2    [b'<div><p>as, data, scientist, working, consu...
3    [b'<div, class="jobsearch-jobmetadataheader, i...
4    [b'<ul><li>location:, usa, \xe2\x80\x93, multi...
Name: tokens, dtype: object

In [93]:

data = []
for token in df['description']:
    data.append(token)

In [94]:
data[0]

'b"<div><div>Job Requirements:</div><ul><li><p>\\nConceptual understanding in Machine Learning models like Nai\\xc2\\xa8ve Bayes, K-Means, SVM, Apriori, Linear/ Logistic Regression, Neural, Random Forests, Decision Trees, K-NN along with hands-on experience in at least 2 of them</p>\\n</li><li><p>Intermediate to expert level coding skills in Python/R. (Ability to write functions, clean and efficient data manipulation are mandatory for this role)</p>\\n</li><li><p>Exposure to packages like NumPy, SciPy, Pandas, Matplotlib etc in Python or GGPlot2, dplyr, tidyR in R</p>\\n</li><li><p>Ability to communicate Model findings to both Technical and Non-Technical stake holders</p>\\n</li><li><p>Hands on experience in SQL/Hive or similar programming language</p>\\n</li><li><p>Must show past work via GitHub, Kaggle or any other published article</p>\\n</li><li><p>Master\'s degree in Statistics/Mathematics/Computer Science or any other quant specific field.</p></li></ul><div><div><div><div><div><d

# 3) Use Scikit-Learn's CountVectorizer to get word counts for each listing.

In [97]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
vectorizer.fit_transform(df['description'])
dtm = vectorizer.transform(df['description'])

In [98]:
dtm = pd.DataFrame(dtm.todense(), columns = vectorizer.get_feature_names())


# 4) Visualize the most common word counts

In [99]:
dtm.head()

00  000  02115  03  0356  04  057  062  06366  08  ...  zero  zeus  zf  \
0   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
1   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
2   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
3   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   
4   0    0      0   0     0   0    0    0      0   0  ...     0     0   0   

   zheng  zillow  zogsports  zones  zoom  zuckerberg  zurich  
0      0       0          0      0     0           0       0  
1      0       0          0      0     0           0       0  
2      0       0          0      0     0           0       0  
3      1       0          0      0     0           0       0  
4      0       0          0      0     0           0       0  

[5 rows x 9202 columns]

 # 5) Use Scikit-Learn's tfidfVectorizer to get a TF-IDF feature matrix

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf = TfidfVectorizer(stop_words='english', max_features=5000)


dtm = tfidf.fit_transform(data)
#dtm = tfidf.transform(new_data)

docs = pd.DataFrame(dtm.todense(), columns = tfidf.get_feature_names())
docs.head()

00  000   04   10  100  1079302   11   12  125   14  ...  yes  yeti  york  \
0  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
1  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
2  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
3  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0      0.0  0.0  0.0  0.0  0.0  ...  0.0   0.0   0.0   

   young  yrs  zenreach  zeus   zf  zillow  zurich  
0    0.0  0.0       0.0   0.0  0.0     0.0     0.0  
1    0.0  0.0       0.0   0.0  0.0     0.0     0.0  
2    0.0  0.0       0.0   0.0  0.0     0.0     0.0  
3    0.0  0.0       0.0   0.0  0.0     0.0     0.0  
4    0.0  0.0       0.0   0.0  0.0     0.0     0.0  

[5 rows x 5000 columns]

 # 6) Create a NearestNeighbor Model. Write the description of your ideal datascience job and query your job listings. 

In [61]:
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')

# Fit on TF-IDF Vectors
nn.fit(dtm.todense())

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [63]:
nn.kneighbors(dtm.todense()[0])

(array([[0.        , 0.86248789, 0.87371026, 0.88181475, 0.88777735]]),
 array([[  0, 276, 301, 264,  71]], dtype=int64))

In [71]:
df['description'][301][:400]

'b"<div><div><div>Facebook\'s mission is to give people the power to build community and bring the world closer together. Through our family of apps and services, we\'re building a different kind of company that connects billions of people around the world, gives them ways to share what matters most to them, and helps bring people closer together. Whether we\'re creating new products or helping a smal'

In [69]:
df['description'][276][:400]

'b"<div><div><div>Facebook\'s mission is to give people the power to build community and bring the world closer together. Through our family of apps and services, we\'re building a different kind of company that connects billions of people around the world, gives them ways to share what matters most to them, and helps bring people closer together. Whether we\'re creating new products or helping a smal'

In [77]:
text =["""Play an integral role in supporting modeling and data analysis, system control, and database needs. Manage large datasets, provide information-based decision logic and predictive modeling solutions, and translate modeling/analytic output into understandable/actionable business knowledge. Provide analytical support and thought leadership. Apply solid financial industry data systems knowledge to support decision and strategy problems in key business areas, strong technical/problem solving skills, and collaboratively manage multiple projects.
Design, develop, implement, and document information-based decision logic and predictive modeling solutions that feed decision logic.

Develop, document, and communicate business-driven analytic solutions and capabilities. Translate modeling and analytic output into understandable and actionable business knowledge.

Provide input, support, and experimental design expertise to insure the statistical significance of marketing test programs and tracking of process improvements.

Manage dataset creation including data extraction, derived and dependent variable creation, and data quality control processes for analytics and model development and validation.

Work closely with fellow managers, technical staff, and business partners to provide analytical support and thought leadership with the goal of developing and implementing information-driven marketing processes and decisions. Ensure analytic solutions are appropriate to existing business processes.

Monitor marketing list generation processes, including list criteria specification, data sourcing, segmentation, analytics, selection, delivery, and back-end data capture of campaign results.
"""]
new = tfidf.transform(text)

nn.kneighbors(new.todense())

(array([[1.27314017, 1.27896315, 1.29158605, 1.29158605, 1.2956833 ]]),
 array([[331,  36, 119, 177, 366]], dtype=int64))

In [78]:
df['description'][331][:500]

'b"POSITION SUMMARY\\n<br/><br/>\\nWe are looking for a passionate, detail-oriented Jr. Data Scientist to join our Data Science team. The successful candidate be responsible for identifying and developing solutions to turn data into actionable business recommendations. You will need to exhibit a strong combination of analytical prowess, technical aptitude and business judgment. You will be expected to focus on results, be a self-starter and demonstrate success in using analytics to drive the unders'

## Stretch Goals

 - Try different visualizations for words and frequencies - what story do you want to tell with the data?
 - Scrape Job Listings for the job title "Data Analyst". How do these differ from Data Scientist Job Listings
 - Try and identify requirements for experience specific technologies that are asked for in the job listings. How are those distributed among the job listings?
 - Use a clustering algorithm to cluster documents by their most important terms. Do the clusters reveal any common themes?
  - **Hint:** K-means might not be the best algorithm for this. Do a little bit of research to see what might be good for this. Also, remember that algorithms that depend on Euclidean distance break down with high dimensional data.